<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Nebula</AssemblyName>
        <RootNamespace>Nebula</RootNamespace>
        <local-interop>..\..\..\..\OneDrive\Desktop\Weird Steam Downloads\Modded Worldless\BepInEx\interop</local-interop>
        <local-libraries>..\..\Libraries\Game Libraries</local-libraries> 
        <remote-libraries>$(MSBuildProjectDirectory)\lib</remote-libraries>

        
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Assembly-CSharp">
         <HintPath Condition="Exists('$(local-libraries)')">$(local-libraries)\Assembly-CSharp.dll</HintPath>
         <HintPath Condition="!Exists('$(local-libraries)')">$(remote-libraries)\Assembly-CSharp-firstpass.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath Condition="Exists('$(local-interop)')">$(local-interop)\Assembly-CSharp-firstpass.dll</HintPath>
        <HintPath Condition="!Exists('$(local-interop)')">$(remote-libraries)\Assembly-CSharp-firstpass.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2Cppmscorlib">
         <HintPath Condition="Exists('$(local-interop)')">$(local-interop)\Il2Cppmscorlib.dll</HintPath>
         <HintPath Condition="!Exists('$(local-interop)')">$(remote-libraries)\Il2Cppmscorlib.dll</HintPath>
         <Private>False</Private>
      </Reference>
      <Reference Include="Noname">
         <HintPath Condition="Exists('$(local-interop)')">$(local-interop)\Noname.dll</HintPath>
         <HintPath Condition="!Exists('$(local-interop)')">$(remote-libraries)\Noname.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Noname.Worldless.Combat">
        <HintPath Condition="Exists('$(local-interop)')">$(local-interop)\Noname.Worldless.Combat.dll</HintPath>
        <HintPath Condition="!Exists('$(local-interop)')">$(remote-libraries)\Noname.Worldless.Combat.dll</HintPath>
        <Private>False</Private>
      </Reference>

      <Reference Include="__Generated">
         <HintPath Condition="Exists('$(local-interop)')">$(local-interop)\__Generated.dll</HintPath>
         <HintPath Condition="!Exists('$(local-interop)')">$(remote-libraries)\__Generated.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\Eva\Hooks\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="BepInEx.Core" Version="6.0.0-*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-*" PrivateAssets="all" />
        <PackageReference Include="Lib.Harmony" Version="2.3.3" PrivateAssets="all" />
        <PackageReference Include="Il2CppInterop.Runtime" Version="1.5.3" PrivateAssets="all" />        
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="UnityEngine.Modules" Version="2022.3.12" PrivateAssets="all" />    
    </ItemGroup>
    
</Project>
