<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Nebula</AssemblyName>
        <RootNamespace>Nebula</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>CamOfFlage.Nebula</PackageId>
        <Authors>CamOfFlage</Authors>
        <Description>A helpful library API for BepInEx modders.</Description>
        <PackageTags>bepinex;modding;unity</PackageTags>
        <RepositoryUrl>https://github.com/CamOfFlage/Nebula</RepositoryUrl>
        <RestoreAdditionalProjectSources>
             https://api.nuget.org/v3/index.json; 
             https://nuget.bepinex.dev/v3/index.json; <!-- For BepInEx -->
        </RestoreAdditionalProjectSources>
        <PrivateAssets>all</PrivateAssets>

    </PropertyGroup>
    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\..\Libraries\Bepinex\0Harmony.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\Libraries\Game Libraries\Assembly-CSharp.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\..\Libraries\Game Libraries\Assembly-CSharp-firstpass.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="BepInEx.Core">
        <HintPath>..\..\Libraries\Bepinex\BepInEx.Core.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="BepInEx.Unity.IL2CPP">
        <HintPath>..\..\Libraries\Bepinex\BepInEx.Unity.IL2CPP.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppInterop.Runtime">
        <HintPath>..\..\Libraries\Bepinex\Il2CppInterop.Runtime.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2Cppmscorlib">
        <HintPath>..\..\..\..\OneDrive\Desktop\Weird Steam Downloads\Modded Worldless\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Noname">
        <HintPath>..\..\..\..\OneDrive\Desktop\Weird Steam Downloads\Modded Worldless\BepInEx\interop\Noname.dll</HintPath>
      </Reference>
      <Reference Include="Noname.Worldless.Combat">
        <HintPath>..\..\Libraries\Game Libraries\Noname.Worldless.Combat.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\..\OneDrive\Desktop\Weird Steam Downloads\Modded Worldless\BepInEx\interop\UnityEngine.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.AnimationModule">
        <HintPath>..\..\..\..\OneDrive\Desktop\Weird Steam Downloads\Modded Worldless\BepInEx\interop\UnityEngine.AnimationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\..\OneDrive\Desktop\Weird Steam Downloads\Modded Worldless\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="__Generated">
        <HintPath>..\..\..\..\OneDrive\Desktop\Weird Steam Downloads\Modded Worldless\BepInEx\interop\__Generated.dll</HintPath>
        <Private>False</Private>
      </Reference>
    <PackageReference Include="BepInEx.Core" Version="6.0.0-*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-*" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\Eva\Hooks\" />
    </ItemGroup>

</Project>
