name: Release Nuget

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      id-token: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore
      
      
      - name: Build and Package Nebula
        # Appends "-dev.RUN_NUMBER" to the base version in your csproj file.
        # e.g., 1.0.0 becomes 1.0.0-dev.5
        run: |
          dotnet pack -c Release /p:VersionSuffix="v${{ github.run_number }}" --output ./nupkg
      
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: Louq # Ensure this is your exact NuGet.org username profile name (not email)

    
      
      - name: Push to NuGet.org
        run: dotnet nuget push "./nupkg/*.nupkg" --source "https://api.nuget.org/v3/index.json" --skip-duplicate --api-key ${{steps.login.outputs.NUGET_API_KEY}}

      - name: Upload Raw DLL File
        uses: actions/upload-artifact@v4
        with:
          name: Nebula-${{ github.run_number }}
          path: bin/Release/net6.0/Nebula.dll

      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            bin/Release/net6.0/Nebula.dll
    
      
